

server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cep
    username: root
    password: well2901
  jpa:
     hibernate:
       ddl-auto: update