

server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/cep
    username: root
    password: 303030
  jpa:
     hibernate:
       ddl-auto: update